#!/bin/bash



while true
do

	clear

	echo "current repositories:"
	ls -I menu

	echo "Enter 1 to create a new repository: "
	echo "Enter 2 to add a file to a repository: "
	echo "Enter 3 to edit an existing file: "
	echo "Enter e to exit this menu: "

	echo -e "\n"
	echo -e "enter your choice "
	read choice

	case $(echo  "$choice" | tr '[:upper:]' '[:lower:]') in

1)
	 echo "Enter name for new repository: "
	 read rName
	 echo "creating " $rName"..."
	 mkdir "$rName"
	 if [ $? -eq 0 ]; then
		date > "$rName/logfile"
		echo "Repository created" >> "$rName/logfile"
		echo " "
	 fi
 	 ;;

2)
	echo "enter the name of the file to move: "
	read fName
	echo "enter the name of the repository you want to add to: "
	read rName

	if [ -e "$fName" ] && [ -d "$rName" ]; then
		mv "$fName" "$rName"
		if [ $?  -eq 0 ]; then
			echo "'$fName' moved to '$rName'"
			date | tee -a "$rName/logfile"
			echo "file added to repository" | tee -a "$rName/logfile"
		else
			echo "failed to move '$fName' to folder"
		fi
	else
		echo "invalid file or directory specified"
		echo "check to see that file or repository exist"
	fi

;;

3)
	echo "Enter the repository containing the file: "
	echo "which of the following repositories contains the file you wish to edit?: "
	ls
	read rName
	cd $rName
	echo "choose a file from the following listing"
	ls
	read choice
	nano $choice
	code $choice
	;;

e|exit)

	echo "exiting the menu"
	exit
	;;
*)
	echo "Invalid choice. try again"

esac


read -n 1 -s -r -p "press any key to continue..."

done
